import { IShapes } from "../ts/interfaces/IShapes";
import { EMPTYSLOTT, SHAPESCOLOR, SHAPESKIND } from "../ts/enums";

export const SHAPES_NAME: SHAPESKIND[] = [
  SHAPESKIND.Z,
  SHAPESKIND.T,
  SHAPESKIND.L,
  SHAPESKIND.O,
  SHAPESKIND.S,
  SHAPESKIND.J,
  SHAPESKIND.I,
];

export const SHAPES: IShapes = {
  Z: {
    tetromino: [
      [SHAPESKIND.Z, SHAPESKIND.Z, EMPTYSLOTT.E],
      [EMPTYSLOTT.E, SHAPESKIND.Z, SHAPESKIND.Z],
      [EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
    ],
    color: SHAPESCOLOR.GREEN,
  },
  T: {
    tetromino: [
      [SHAPESKIND.T, SHAPESKIND.T, SHAPESKIND.T],
      [EMPTYSLOTT.E, SHAPESKIND.T, EMPTYSLOTT.E],
      [EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
    ],
    color: SHAPESCOLOR.PURPLE,
  },
  L: {
    tetromino: [
      [SHAPESKIND.L, EMPTYSLOTT.E, EMPTYSLOTT.E],
      [SHAPESKIND.L, EMPTYSLOTT.E, EMPTYSLOTT.E],
      [SHAPESKIND.L, SHAPESKIND.L, EMPTYSLOTT.E],
    ],
    color: SHAPESCOLOR.ORANGE,
  },
  O: {
    tetromino: [
      [SHAPESKIND.O, SHAPESKIND.O],
      [SHAPESKIND.O, SHAPESKIND.O],
    ],
    color: SHAPESCOLOR.YELLOW,
  },
  S: {
    tetromino: [
      [EMPTYSLOTT.E, SHAPESKIND.S, SHAPESKIND.S],
      [SHAPESKIND.S, SHAPESKIND.S, EMPTYSLOTT.E],
      [EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
    ],
    color: SHAPESCOLOR.RED,
  },
  J: {
    tetromino: [
      [EMPTYSLOTT.E, EMPTYSLOTT.E, SHAPESKIND.J],
      [EMPTYSLOTT.E, EMPTYSLOTT.E, SHAPESKIND.J],
      [EMPTYSLOTT.E, SHAPESKIND.J, SHAPESKIND.J],
    ],
    color: SHAPESCOLOR.PINK,
  },
  I: {
    tetromino: [
      [SHAPESKIND.I, EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
      [SHAPESKIND.I, EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
      [SHAPESKIND.I, EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
      [SHAPESKIND.I, EMPTYSLOTT.E, EMPTYSLOTT.E, EMPTYSLOTT.E],
    ],
    color: SHAPESCOLOR.PINK,
  },
};
