import { Shapes } from '../ts/interfaces/Shapes';
import { SHAPESCOLOR, SHAPESKIND } from '../ts/enums';

export const SHAPES_NAME: string[] = ['Z', 'T', 'L', 'O', 'S', 'J', 'I'];
export const BOARD_HEIGHT: number = 20;
export const BOARD_WIDTH: number = 10;

export const SHAPES: Shapes = {
  Z: {
    shape: [
      [SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.Z, SHAPESKIND.Z, SHAPESKIND.E],
      [SHAPESKIND.E, SHAPESKIND.Z, SHAPESKIND.Z],
    ],
    color: SHAPESCOLOR.GREEN,
  },
  T: {
    shape: [
      [SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.T, SHAPESKIND.T, SHAPESKIND.T],
      [SHAPESKIND.E, SHAPESKIND.T, SHAPESKIND.E],
    ],
    color: SHAPESCOLOR.PURPLE,
  },
  L: {
    shape: [
      [SHAPESKIND.L, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.L, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.L, SHAPESKIND.L, SHAPESKIND.E],
    ],
    color: SHAPESCOLOR.ORANGE,
  },
  O: {
    shape: [
      [SHAPESKIND.O, SHAPESKIND.O],
      [SHAPESKIND.O, SHAPESKIND.O],
    ],
    color: SHAPESCOLOR.YELLOW,
  },
  S: {
    shape: [
      [SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.E, SHAPESKIND.S, SHAPESKIND.S],
      [SHAPESKIND.S, SHAPESKIND.S, SHAPESKIND.E],
    ],
    color: SHAPESCOLOR.RED,
  },
  J: {
    shape: [
      [SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.J],
      [SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.J],
      [SHAPESKIND.E, SHAPESKIND.J, SHAPESKIND.J],
    ],
    color: SHAPESCOLOR.PINK,
  },
  I: {
    shape: [
      [SHAPESKIND.I, SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.I, SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.I, SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
      [SHAPESKIND.I, SHAPESKIND.E, SHAPESKIND.E, SHAPESKIND.E],
    ],
    color: SHAPESCOLOR.PINK,
  },
};
